# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
        config:
          description: '配置文件名'
          required: true
          default: 'mipsel.config'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  crosstool:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
  
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "apt-get init"
        run: |
            pwd
            sudo apt-get install -y gperf help2man libtool-bin

      # Runs a set of commands using the runners shell
      - name: "Run git clone"
        run: |
          git clone https://github.com/crosstool-ng/crosstool-ng.git
      - name: "run make"
        run : |
          cd ./crosstool-ng
          ./bootstrap
          ./configure --prefix=$PWD/.build/
          make
          make install
          .build/bin/ct-ng help
          tar -zcvf $GITHUB_WORKSPACE/ct-ng.tar.gz .build/
      - name: "upload ct-ng"
        uses: actions/upload-artifact@v2
        with:
          name: crosstool
          path: ct-ng.tar.gz    
  
  toolchains:
    needs: crosstool
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "download ct-ng"
        uses: actions/download-artifact@v2
        with:
          name: crosstool
      - name: "extract ct-ng"
        run: |
          mkdir -p $GITHUB_WORKSPACE/crosstool-ng
          tar -zxvf ct-ng.tar.gz -C $GITHUB_WORKSPACE/crosstool-ng

      - name: "prereq"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          sudo apt-get install -y gperf help2man libtool-bin
          echo "::add-path::$GITHUB_WORKSPACE/crosstool-ng/.build/bin"
      - name: "build"
        run: |
            mv "${{github.event.inputs.config}}" .config
            ct-ng build
            echo  $GITHUB_WORKSPACE
            tar -zcvf $GITHUB_WORKSPACE/x-tools.tar.gz /home/runner/x-tools/
      - name: "upload x-tools"
        uses: actions/upload-artifact@v2
        with:
          name: x-tools
          path: x-tools.tar.gz
      - name: "created releases"
        uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                automatic_release_tag: "${{github.event.inputs.config}}"
                prerelease: false
                files: |
                  test.tar.gz       
          


          
              
