name: test
on:
    workflow_dispatch:
      inputs:
        par1:
          description: '参数1'
          required: true
          default: ''
        par2:
          description: '参数2'
          required: false
      
jobs:
    test1:
        runs-on:
            ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2
            - name: "test gz"
              run: |
                  pwd
                  mkdir -p ./test
                  cd ./test
                  dd if=/dev/zero of=test bs=1M count=100
                  cd ../
                  tar -zcvf test.tar.gz ./test
            - name: "upload"
              uses: actions/upload-artifact@v2
              with:
                name: crosstool
                path: test.tar.gz