name: test
on:
    workflow_dispatch:
      inputs:
        config:
          description: '参数1'
          required: true
          default: 'mipsel.config'
      
jobs:
    test1:
        runs-on:
            ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2
            - name: "test gz"
              run: |
                  pwd
                  mkdir -p ./test
                  cd ./test
                  dd if=/dev/zero of=test bs=1M count=10
                  cd ../
                  echo ${{inputs.config}}
                  tar -zcvf test.tar.gz ./test
            - name: "upload"
              uses: actions/upload-artifact@v2
              with:
                name: crosstool
                path: test.tar.gz